// Code generation modules
pub mod ir_builder;
pub mod verilog_gen;
pub use paste;

use std::collections::{HashMap, HashSet};
use std::fs;

use ir_builder::IRBuilder;
use verilog_gen::VerilogGenerator;
use syn::parse_str;

/// Generate Verilog from stringified Rust function code
pub fn to_verilog_from_str(rust_code: &str) -> String {
    // Parse Rust AST
    match parse_str::<syn::ItemFn>(rust_code) {
        Ok(func) => {
            // Build IR from Rust AST
            match IRBuilder::from_function(&func) {
                Ok(ir) => {
                    // Generate Verilog from IR
                    VerilogGenerator::generate(&ir)
                }
                Err(e) => format!("// Error building IR: {}\n", e),
            }
        }
        Err(e) => format!("// Error parsing function: {}\n", e),
    }
}

/// Generate Verilog from stringified Rust function code with source-file dependency context.
pub fn to_verilog_from_str_with_source(rust_code: &str, source_file: &str) -> String {
    match parse_str::<syn::ItemFn>(rust_code) {
        Ok(func) => {
            let deps = load_functions_from_source(source_file).unwrap_or_default();
            let mut visited = HashSet::new();
            match generate_module_with_dependencies(&func, &deps, &mut visited) {
                Ok(verilog) => verilog,
                Err(e) => format!("// Error building IR: {}\n", e),
            }
        }
        Err(e) => format!("// Error parsing function: {}\n", e),
    }
}

fn generate_module_with_dependencies(
    func: &syn::ItemFn,
    deps: &HashMap<String, syn::ItemFn>,
    visited: &mut HashSet<String>,
) -> Result<String, String> {
    let module_name = func.sig.ident.to_string();
    if visited.contains(&module_name) {
        return Ok(String::new());
    }
    visited.insert(module_name.clone());

    let ir = IRBuilder::from_function_with_deps(func, deps)?;

    let mut dep_text = String::new();
    for inst in &ir.submodules {
        if let Some(dep_fn) = deps.get(&inst.module_name) {
            let nested = generate_module_with_dependencies(dep_fn, deps, visited)?;
            if !nested.is_empty() {
                dep_text.push_str(&nested);
                dep_text.push('\n');
            }
        }
    }

    let module_text = VerilogGenerator::generate(&ir);
    if dep_text.is_empty() {
        Ok(module_text)
    } else {
        Ok(format!("{}{}", dep_text, module_text))
    }
}

fn load_functions_from_source(source_file: &str) -> Result<HashMap<String, syn::ItemFn>, String> {
    let source_text = fs::read_to_string(source_file)
        .map_err(|e| format!("Failed to read source file '{}': {}", source_file, e))?;

    let parsed = syn::parse_file(&source_text)
        .map_err(|e| format!("Failed to parse source file '{}': {}", source_file, e))?;

    let mut map = HashMap::new();
    for item in parsed.items {
        if let syn::Item::Fn(func) = item {
            map.insert(func.sig.ident.to_string(), func);
        }
    }

    Ok(map)
}

/// Macro to generate Verilog from a function
/// Usage: verilog!(function_name)
#[macro_export]
macro_rules! verilog {
    ($func:item) => {
        $crate::to_verilog_from_str(stringify!($func))
    };
}

/// Macro to generate Verilog from a `#[hardware]` module name.
///
/// This resolves and calls the helper generated by `#[hardware]` without
/// requiring users to know the internal `<name>_verilog` naming convention.
///
/// Usage: `module_verilog!(inverter)`
#[macro_export]
macro_rules! module_verilog {
    ($module:ident) => {{
        $crate::paste::paste! {
            [<$module _verilog>]()
        }
    }};
}

/// User-friendly alias for module-based Verilog generation.
///
/// Usage: `to_verilog!(inverter)`
#[macro_export]
macro_rules! to_verilog {
    ($module:ident) => {
        $crate::module_verilog!($module)
    };
}
