//! Generates one differential equivalence test per `#[hardware]` module in
//! `tests/fixtures/` — phase 2 of `design_docs/CORPUS_DIFFERENTIAL_SWEEP.md`.
//!
//! Each generated case runs the module in the simulator under seeded random
//! stimulus and Verilates the SystemVerilog it transpiles to against that trace,
//! cycle by cycle. No reference model is involved: the simulator and the emitted SV
//! are two independent implementations of one source, so comparing them is already
//! an oracle. That is what makes the case *generatable*, and generatable is what
//! makes the coverage complete instead of "whatever anybody got round to".
//!
//! The output is `$OUT_DIR/corpus_generated.rs`, `include!`d by
//! `tests/corpus_generated.rs`. **A skipped module still gets a test**, marked
//! `#[ignore]` with its reason, because a check that silently does not run is this
//! repo's most-repeated bug class (see the G-A/G-B/G-C guards in
//! `tools/regression.sh`) and a sweep is exactly the wrong place to reintroduce it.
//!
//! # Why a build script and not a proc macro
//!
//! A proc macro reading files off disk has no rebuild tracking: edit a fixture and
//! its generated test silently stays stale. `cargo:rerun-if-changed` below is the
//! whole reason this is a build script.
//!
//! # Known limitation
//!
//! Port names are used verbatim. The generated testbench addresses the Verilated
//! model by the **emitted** name, and a name that collides with a SystemVerilog or
//! C++ keyword is legalized (`event` → `event_sig`), so such a fixture would fail
//! loudly with a C++ compile error rather than being handled. No fixture has one
//! today; wiring the rust→SV mapping through is phase 3's job.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use quote::ToTokens;

/// Modules the sweep must not run, each with the reason it cannot. Kept here, in
/// version control and in review, rather than inferred: "this one is expected to
/// fail" is a claim that should have an author and a sentence.
const SKIP: &[(&str, &str)] = &[
    (
        "mp_rom",
        "refused by design: a plain `Out` driven from a memory read result across phases has no \
         correct emitted form (measured a full cycle late). multiphase_memory_equivalence.rs pins \
         the diagnostic",
    ),
    (
        "tick_first_waiter",
        "refused by design: a repeating wait must be written test-first; pinned as an unsupported \
         construct in unsupported_constructs.rs",
    ),
    (
        "probe",
        "an `allow_pretick_alignment` witness: the module exists to DEMONSTRATE the pre-tick \
         divergence, so sim ≠ SV is its purpose. probe_timing_investigation.rs measures it",
    ),
    (
        "probe_fsm",
        "a pinned divergence (probe_fsm_sim_matches_verilog is #[ignore]d for it): a phase-gated \
         cross-tick read still disagrees with the transpiler",
    ),
    (
        "branch_merge_explicit",
        "MEASURED DIVERGENCE, pinned as sequential_forwarding_divergence.rs::\
         a_write_in_a_state_arm_leads_the_hardware_by_one_cycle and written up in \
         PRETICK_ALIGNMENT_GUARDRAIL.md 5.5 — the simulator leads the identical emitted SV by one \
         cycle. Un-ignore when the constant-write exemption is narrowed",
    ),
];

/// Cycles of random stimulus per sequential module.
const SEQ_CYCLES: usize = 200;
/// Random input vectors per combinational module (no clock, so `poll_tasks`).
const COMB_VECTORS: usize = 64;

fn main() {
    println!("cargo:rerun-if-changed=tests/fixtures");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let fixtures = manifest.join("tests/fixtures");

    let mut files: Vec<PathBuf> = std::fs::read_dir(&fixtures)
        .expect("tests/fixtures is readable")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "rs"))
        .collect();
    files.sort();

    let mut code = String::from(
        "// @generated by build.rs — phase 2 of design_docs/CORPUS_DIFFERENTIAL_SWEEP.md.\n\
         // Edit build.rs, not this file.\n\n",
    );
    let (mut emitted, mut ignored) = (0usize, 0usize);
    let mut covered: Vec<String> = Vec::new();

    for path in &files {
        let src = std::fs::read_to_string(path).expect("fixture is readable");
        let file = match syn::parse_file(&src) {
            Ok(f) => f,
            // A fixture that does not parse standalone is not this script's problem
            // to report — the test that includes it will say so far more clearly.
            Err(_) => continue,
        };
        let modules: Vec<Module> = file.items.iter().filter_map(Module::from_item).collect();
        if modules.is_empty() {
            continue;
        }
        let (m, i) = emit_file(&mut code, path, &modules);
        emitted += m;
        ignored += i;
        covered.extend(modules.iter().map(|m| m.name.clone()));
    }

    // The manifest the coverage guard checks against: every module this script
    // emitted a case for, ignored ones included. A generator that quietly stops
    // covering something is the failure mode this whole file exists to prevent, so
    // it is asserted in the test binary rather than trusted.
    let _ = writeln!(
        code,
        "/// Every fixture module `build.rs` emitted a case for (ignored ones too).\n\
         pub const COVERED: &[&str] = &[{}];",
        covered.iter().map(|n| format!("\"{n}\"")).collect::<Vec<_>>().join(", ")
    );

    // Surfaced in the build log too, so the counts are visible without running.
    println!("cargo:warning=corpus sweep: {emitted} generated, {ignored} ignored-with-reason");
    std::fs::write(out_dir.join("corpus_generated.rs"), code).expect("write generated tests");
}

/// One `#[hardware]` module, as much of it as generation needs.
struct Module {
    name: String,
    /// `true` for a const-generic module: `copper-transpile` only handles concrete
    /// ones (generics are monomorphized by the macro at run time), so it cannot be
    /// swept as it stands.
    generic: bool,
    ports: Vec<Port>,
}

struct Port {
    name: String,
    /// The payload type as written (`Bits<8>`, `Logic`), or the domain for a clock.
    ty: String,
    domain: String,
    kind: Kind,
}

#[derive(PartialEq)]
enum Kind {
    Clock,
    In,
    Out,
    RegOut,
}

impl Module {
    fn from_item(item: &syn::Item) -> Option<Module> {
        let syn::Item::Fn(f) = item else { return None };
        if !f.attrs.iter().any(|a| {
            a.path().segments.last().is_some_and(|s| s.ident == "hardware")
        }) {
            return None;
        }
        let mut ports = Vec::new();
        for arg in &f.sig.inputs {
            let syn::FnArg::Typed(pt) = arg else { return None };
            let name = pt.pat.to_token_stream().to_string();
            let (kind, ty, domain) = classify(&pt.ty)?;
            ports.push(Port { name, ty, domain, kind });
        }
        Some(Module {
            name: f.sig.ident.to_string(),
            generic: !f.sig.generics.params.is_empty(),
            ports,
        })
    }

    fn clock(&self) -> Option<&Port> {
        self.ports.iter().find(|p| p.kind == Kind::Clock)
    }

    /// The reason this module cannot be swept, if any.
    fn skip_reason(&self) -> Option<String> {
        if let Some((_, why)) = SKIP.iter().find(|(n, _)| *n == self.name) {
            return Some((*why).to_string());
        }
        if self.generic {
            return Some(
                "generic module: monomorphized by the macro at run time, so `copper-transpile` \
                 (concrete modules only) cannot emit it. Sweeping it needs the `with_params` \
                 monomorphization path — phase 4"
                    .to_string(),
            );
        }
        if self.ports.iter().any(|p| p.kind != Kind::Clock && !is_stimulable(&p.ty)) {
            return Some(format!(
                "unsupported port payload: the generator can only randomise `Logic` and \
                 `Bits<N>` ({})",
                self.ports
                    .iter()
                    .filter(|p| p.kind != Kind::Clock && !is_stimulable(&p.ty))
                    .map(|p| format!("{}: {}", p.name, p.ty))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        None
    }
}

/// `In<Bits<8>, MainClk>` → `(Kind::In, "Bits<8>", "MainClk")`; `Clock<D>` → the domain.
fn classify(ty: &syn::Type) -> Option<(Kind, String, String)> {
    let syn::Type::Path(tp) = ty else { return None };
    let seg = tp.path.segments.last()?;
    let kind = match seg.ident.to_string().as_str() {
        "Clock" => Kind::Clock,
        "In" => Kind::In,
        "Out" => Kind::Out,
        "RegOut" => Kind::RegOut,
        _ => return None,
    };
    let syn::PathArguments::AngleBracketed(args) = &seg.arguments else { return None };
    let text: Vec<String> = args
        .args
        .iter()
        .map(|a| a.to_token_stream().to_string().replace(' ', ""))
        .collect();
    match kind {
        Kind::Clock => Some((kind, text.first()?.clone(), text.first()?.clone())),
        _ => Some((kind, text.first()?.clone(), text.get(1)?.clone())),
    }
}

/// Can seeded random stimulus be generated for this payload? `RandStim` covers
/// `Logic` and any concrete `Bits<N>`; a const-generic width or an array port is
/// left to a later phase rather than guessed at.
fn is_stimulable(ty: &str) -> bool {
    if ty == "Logic" {
        return true;
    }
    ty.strip_prefix("Bits<")
        .and_then(|r| r.strip_suffix('>'))
        .is_some_and(|w| w.chars().all(|c| c.is_ascii_digit()) && !w.is_empty())
}

/// A zero of the payload type, for the wire's initial value.
fn zero_of(ty: &str) -> &'static str {
    if ty == "Logic" { "Logic::Zero" } else { "Bits::zero()" }
}

/// A stable per-module seed, so two modules do not walk the same bit pattern and a
/// failure is reproducible from the name alone (FNV-1a).
fn seed_of(name: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in name.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x1000_0000_01b3);
    }
    h | 1
}

/// Emit the wrapper module for one fixture file plus a test per hardware module.
/// Returns `(generated, ignored)`.
fn emit_file(code: &mut String, path: &Path, modules: &[Module]) -> (usize, usize) {
    let stem = path.file_stem().expect("fixture has a stem").to_string_lossy().to_string();
    let file_path = path.to_string_lossy();

    // Every clock domain the file's modules mention. Fixtures declare none of their
    // own — by design, so the including test picks them — so the wrapper declares
    // them all. `()` is already a `ClockDomain` and must not be redeclared.
    let domains: BTreeSet<&str> = modules
        .iter()
        .flat_map(|m| m.ports.iter())
        .map(|p| p.domain.as_str())
        .filter(|d| *d != "()")
        .collect();

    let _ = writeln!(code, "#[allow(unused_imports, dead_code)]");
    let _ = writeln!(code, "mod fx_{stem} {{");
    let _ = writeln!(
        code,
        "    use copper_core::port::{{registered_wire, wire, In, Out, RegOut}};\n    \
         use copper_core::types::Bits;\n    \
         use copper_core::{{Clock, ClockDomain, Logic, Memory}};\n    \
         use copper_macros::hardware;\n    \
         use copper_sim::HardwareExecutor;\n    \
         use crate::common::{{EquivalenceTest, RandStim, Rng}};"
    );
    for d in &domains {
        let _ = writeln!(code, "    struct {d};\n    impl ClockDomain for {d} {{}}");
    }
    let _ = writeln!(code, "    include!(\"{file_path}\");");
    let _ = writeln!(code, "    const SRC: &str = include_str!(\"{file_path}\");\n");

    let (mut emitted, mut ignored) = (0, 0);
    for m in modules {
        match m.skip_reason() {
            Some(reason) => {
                let _ = writeln!(code, "    #[ignore = \"{}\"]", escape(&reason));
                emit_test(code, m, /*body=*/ false);
                ignored += 1;
            }
            None => {
                emit_test(code, m, true);
                emitted += 1;
            }
        }
    }
    let _ = writeln!(code, "}}\n");
    (emitted, ignored)
}

/// The test itself. With `body == false` the case is `#[ignore]`d and the body is a
/// single `panic!` — it must still *exist* (so the skip is listed and counted), and
/// it must not be silently green if someone removes the `#[ignore]`.
fn emit_test(code: &mut String, m: &Module, body: bool) {
    let name = &m.name;
    let _ = writeln!(code, "    #[test]");
    let _ = writeln!(code, "    fn {name}_differential() {{");
    if !body {
        let _ = writeln!(
            code,
            "        panic!(\"skipped by build.rs's SKIP table — see the #[ignore] reason\");"
        );
        let _ = writeln!(code, "    }}\n");
        return;
    }

    let clk = m.clock();
    let _ = writeln!(
        code,
        "        let mut eq = EquivalenceTest::differential_only(\"{name}\", SRC, Some(\"{name}\"));"
    );
    let _ = writeln!(code, "        let mut rng = Rng::new({});", seed_of(name));
    if let Some(c) = clk {
        let _ = writeln!(code, "        let mut clk = Clock::<{}>::new();", c.domain);
    }
    let _ = writeln!(code, "        let mut exec = HardwareExecutor::new();");

    for p in &m.ports {
        match p.kind {
            Kind::Clock => {}
            Kind::In => {
                let _ = writeln!(
                    code,
                    "        let ({n}_drv, {n}_in) = wire::<{ty}, {d}>({z});",
                    n = p.name,
                    ty = p.ty,
                    d = p.domain,
                    z = zero_of(&p.ty)
                );
            }
            Kind::Out => {
                let _ = writeln!(
                    code,
                    "        let ({n}_out, {n}_obs) = wire::<{ty}, {d}>({z});",
                    n = p.name,
                    ty = p.ty,
                    d = p.domain,
                    z = zero_of(&p.ty)
                );
            }
            Kind::RegOut => {
                let _ = writeln!(
                    code,
                    "        let ({n}_out, {n}_obs) = registered_wire::<{ty}, {d}>(&clk, {z});",
                    n = p.name,
                    ty = p.ty,
                    d = p.domain,
                    z = zero_of(&p.ty)
                );
            }
        }
    }

    let handles: Vec<String> = m
        .ports
        .iter()
        .filter(|p| matches!(p.kind, Kind::Out | Kind::RegOut))
        .map(|p| format!("{}_out.dirty_handle()", p.name))
        .collect();
    let reads: Vec<String> = m
        .ports
        .iter()
        .filter(|p| p.kind == Kind::In)
        .map(|p| format!("{}_in.wire_id()", p.name))
        .collect();
    let _ = writeln!(code, "        let handles = vec![{}];", handles.join(", "));
    let _ = writeln!(code, "        let reads = vec![{}];", reads.join(", "));

    // Arguments in SIGNATURE order — not inputs-then-outputs, which is merely the
    // usual convention and not a rule any fixture is obliged to follow.
    let args: Vec<String> = m
        .ports
        .iter()
        .map(|p| match p.kind {
            Kind::Clock => "clk.clone()".to_string(),
            Kind::In => format!("{}_in", p.name),
            Kind::Out | Kind::RegOut => format!("{}_out", p.name),
        })
        .collect();
    let _ = writeln!(
        code,
        "        exec.spawn_wired({name}({}), handles, reads);\n",
        args.join(", ")
    );

    let cycles = if clk.is_some() { SEQ_CYCLES } else { COMB_VECTORS };
    let _ = writeln!(code, "        for _ in 0..{cycles} {{");
    for p in m.ports.iter().filter(|p| p.kind == Kind::In) {
        let _ = writeln!(
            code,
            "            let {n}_v = <{ty} as RandStim>::rand(&mut rng);\n            \
             {n}_drv.write({n}_v);",
            n = p.name,
            ty = p.ty
        );
    }
    let _ = writeln!(
        code,
        "            {}",
        if clk.is_some() { "exec.tick_clock(&mut clk);" } else { "exec.poll_tasks();" }
    );
    for p in m.ports.iter().filter(|p| matches!(p.kind, Kind::Out | Kind::RegOut)) {
        let _ = writeln!(code, "            let {n}_v = {n}_obs.read();", n = p.name);
    }
    let ins: Vec<String> = m
        .ports
        .iter()
        .filter(|p| p.kind == Kind::In)
        .map(|p| format!("(\"{n}\", &{n}_v.as_bits()[..])", n = p.name))
        .collect();
    let outs: Vec<String> = m
        .ports
        .iter()
        .filter(|p| matches!(p.kind, Kind::Out | Kind::RegOut))
        .map(|p| format!("(\"{n}\", &{n}_v.as_bits()[..])", n = p.name))
        .collect();
    let _ = writeln!(
        code,
        "            eq.record_differential(&[{}], &[{}]);",
        ins.join(", "),
        outs.join(", ")
    );
    let _ = writeln!(code, "        }}");
    let _ = writeln!(code, "        eq.finish();");
    let _ = writeln!(code, "    }}\n");
}

/// Escape a reason string for a `#[ignore = "…"]` attribute.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
