[workspace]
resolver = "3"
members = ["copper-core", "copper-macros", "copper-codegen", "copper-sim"]

[package]
name = "copper"
version = "0.1.0"
edition = "2024"

[dependencies]
copper-core = { path = "copper-core" }
copper-macros = { path = "copper-macros" }
copper-codegen = { path = "copper-codegen" }
copper-sim = { path = "copper-sim" }
env_logger = "0.11.8"
log = "0.4.29"

[[example]]
name = "one_bit_comparator"
path = "examples/combinational/one_bit_comparator.rs"

[[example]]
name = "mux"
path = "examples/combinational/mux.rs"

[[example]]
name = "ripple_carry_adder"
path = "examples/combinational/ripple_carry_adder.rs"

[[example]]
name = "rotate_right"
path = "examples/combinational/rotate_right.rs"

[[example]]
name = "priority_encode"
path = "examples/combinational/priority_encode.rs"

[[example]]
name = "shift_register"
path = "examples/sequential/shift_register.rs"

[[example]]
name = "pattern_detector"
path = "examples/sequential/pattern_detector.rs"

[[example]]
name = "traffic_light_fsm"
path = "examples/sequential/traffic_light_fsm.rs"

[[example]]
name = "pipeline_mac"
path = "examples/sequential/pipeline_mac.rs"

[[example]]
name = "lfsr"
path = "examples/sequential/lfsr.rs"

[[example]]
name = "dual_port_ram"
path = "examples/memory/dual_port_ram.rs"

[[example]]
name = "rv32i_cpu"
path = "examples/cpu/rv32i_cpu.rs"

[[example]]
name = "rv32i_cpu_pipelined"
path = "examples/cpu/rv32i_cpu_pipelined.rs"

[[example]]
name = "uart_rx"
path = "examples/uart/rx.rs"

[[example]]
name = "uart_system"
path = "examples/uart/system.rs"

[[example]]
name = "two_domain_counter"
path = "examples/cdc/two_domain_counter.rs"
